### PR TITLE
Silverstripe 4 migration

### PR DESCRIPTION
**Pull request by ggrune**
Please take a look. I have tried to migrate the photogallery to Silverstripe 4

### CODE REVIEW

**Comment by andrewhoule** [comment]
This looks great, thanks!!! I just tried things quick... Looks like the sliderfield hasn't been upgraded to SS4 yet, so I'm getting conflicts there. I'm going to try to drop that dependency, and create an SS 3 branch to keep around before merging this into the master branch.

**Comment by ggrune** [comment]
There are some other issues with SS4. 
If you upload new images the files are protected and you have to publish every image in the file management. The images should be public by default.

**Comment by andrewhoule** [comment]
Gotcha, I'm hoping to get some time to fix it all up soon. Thanks for the head start!

**Comment by andrewhoule** [comment]
This module now works with SS 4.

**Pull request closed without merging**
